version: "3"

services:

  web:
    build: .
    container_name: web
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    build:
      context: ./db
    volumes:
    - ./db/data/:/var/lib/postgresql/data
    container_name: db
    environment:
         - POSTGRES_PASSWORD=kagan123
         - POSTGRES_USER=postgres
    restart: unless-stopped
